AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: rssfeed - template for script that sends RSS feed entries to a Discord webhook.

Parameters:
  WebhookUrl:
    Type: String
    Description: URL for the Discord webhook

Globals:
  Function:
    Timeout: 16
    MemorySize: 128

Resources:
  RssFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref rssfeedtable
      Environment:
        Variables:
          TABLE_NAME: !Ref rssfeedtable
          WEBHOOK_URL: !Ref WebhookUrl
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(3 minutes)

  rssfeedtable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rssfeeds
        AttributeDefinitions:
          -
            AttributeName: feed
            AttributeType: S
        KeySchema:
          -
            AttributeName: feed
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5