name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          mkdir -p package/python/lib/python3.8/site-packages
          pip install -r requirements.txt -t package/python/lib/python3.8/site-packages/

      - name: Package and deploy to AWS Lambda
        run: |
          cd package && zip -r ../lambda_function_payload.zip . 
          cd .. && zip -g lambda_function_payload.zip -r src/
          aws lambda update-function-code --function-name RSSFeedProcessor --zip-file fileb://lambda_function_payload.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'


       

